### ISSUE TITLE
[question] Want et al. 2015

### ISSUE THREAD

**Issue by natowi** [bldeng/MeshSDFilter#2]
In https://github.com/bldeng/MeshSDFilter/blob/master/MeshNormalFilter.h
you cite "Poisson-based update from [Want et al. 2015]".

I think this is a typo and should be P. Wang, X. Fu, Y. Liu, X. Tong, S. Liu, and B. Guo, “Rolling guidancenormal filter for geometric processing,”ACM Trans. Graph., vol. 34,no. 6, p. 173, 2015

**Comment by bldeng** [comment]
That should be [Wang et al. 2015] as in the paper, referring to the following publication:
- Wang, P.S., Fu, X.M., Liu, Y., Tong, X., Liu, S.L. and Guo, B., 2015. Rolling guidance normal filter for geometric processing. ACM Transactions on Graphics (TOG), 34(6)

The file has been updated now to fix the typo.
